# Generated by Django 5.2.6 on 2025-09-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_registrationpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('garzon', 'Garzón'), ('cocinero', 'Cocinero'), ('admin', 'Administrador')], default='garzon', max_length=20),
        ),
    ]
