# Generated by Django 5.2.6 on 2025-09-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationpin',
            name='used',
        ),
        migrations.AddField(
            model_name='registrationpin',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
