# Generated by Django 5.2.6 on 2025-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_registrationpin_used_registrationpin_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_taken', 'Pedido sin tomar'), ('preparing', 'En preparación'), ('ready', 'Listo'), ('delivered', 'Entregado')], default='not_taken', max_length=20),
        ),
    ]
