# Generated by Django 5.2.6 on 2025-09-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_table_is_available_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpin',
            name='role',
            field=models.CharField(choices=[('garzon', 'Garzón'), ('cocinero', 'Cocinero'), ('admin', 'Administrador'), ('recepcion', 'Recepción')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('garzon', 'Garzón'), ('cocinero', 'Cocinero'), ('admin', 'Administrador'), ('recepcion', 'Recepción')], default='garzon', max_length=20),
        ),
    ]
